CXXFLAGS	= -std=c++11 -Wall -O3
MAKEFLAGS	+= --silent

# CPP_SRCS = $(wildcard *.cpp)
# CPP_PROGS = $(patsubst %.cpp, %, $(CPP_SRCS))

all: #$(CPP_PROGS)
	bash ./handle_ai.sh

# %: %.cpp
# 	echo "$(CXX) $(CXXFLAGS) $(CFLAGS) -o $@.ai $<"
# 	$(CXX) $(CXXFLAGS) $(CFLAGS) -o $@.ai $<



